// export const emailData = [
//     {
//       id: 1,
//       sender: "John Doe",
//       subject: "Meeting Reminder",
//       body: "Just a reminder about tomorrow's meeting at 10 AM.",
//       date: "Oct 15, 2024",
//       isRead: false,
//     },
//     {
//       id: 2,
//       sender: "Jane Smith",
//       subject: "Project Update",
//       body: "Please review the latest project updates.",
//       date: "Oct 14, 2024",
//       isRead: true,
//     },
//     {
//       id: 3,
//       sender: "Company Newsletter",
//       subject: "October Newsletter",
//       body: "Check out our latest updates for October.",
//       date: "Oct 12, 2024",
//       isRead: true,
//     },
//     {
//       id: 4,
//       sender: "Support Team",
//       subject: "Ticket Resolved",
//       body: "Your support ticket has been successfully resolved.",
//       date: "Oct 11, 2024",
//       isRead: false,
//     },
//     {
//       id: 5,
//       sender: "Alice Brown",
//       subject: "Lunch Plans",
//       body: "Let's have lunch sometime this week.",
//       date: "Oct 10, 2024",
//       isRead: true,
//     },
//     {
//       id: 6,
//       sender: "HR Department",
//       subject: "Policy Update",
//       body: "We've updated the company policies. Please review the changes.",
//       date: "Oct 09, 2024",
//       isRead: true,
//     },
//     {
//       id: 7,
//       sender: "Bob Anderson",
//       subject: "Travel Itinerary",
//       body: "Your travel itinerary has been finalized. Please find the details attached.",
//       date: "Oct 08, 2024",
//       isRead: false,
//     },
//     {
//       id: 8,
//       sender: "Marketing Team",
//       subject: "Exclusive Offer",
//       body: "Get 30% off on your next purchase! Offer valid till end of October.",
//       date: "Oct 07, 2024",
//       isRead: true,
//     },
//     {
//       id: 9,
//       sender: "Sara Lee",
//       subject: "Re: Client Feedback",
//       body: "Thanks for sending the feedback. I’ll make the necessary updates.",
//       date: "Oct 06, 2024",
//       isRead: false,
//     },
//     {
//       id: 10,
//       sender: "IT Support",
//       subject: "Password Reset",
//       body: "You requested a password reset. Click here to reset your password.",
//       date: "Oct 05, 2024",
//       isRead: true,
//     },
//     {
//       id: 11,
//       sender: "John Appleseed",
//       subject: "Reminder: Annual Performance Review",
//       body: "Don't forget about your annual performance review next week.",
//       date: "Oct 04, 2024",
//       isRead: false,
//     },
//     {
//       id: 12,
//       sender: "LinkedIn Updates",
//       subject: "You have new connection requests",
//       body: "View your new connection requests and messages.",
//       date: "Oct 03, 2024",
//       isRead: true,
//     },
//     {
//       id: 13,
//       sender: "Conference Organizer",
//       subject: "Upcoming Conference Details",
//       body: "Join us for the upcoming tech conference. Registration is open.",
//       date: "Oct 02, 2024",
//       isRead: false,
//     },
//     {
//       id: 14,
//       sender: "Netflix",
//       subject: "New Releases",
//       body: "Check out the new movies and shows available this week.",
//       date: "Oct 01, 2024",
//       isRead: true,
//     },
//     {
//       id: 15,
//       sender: "Google Alerts",
//       subject: "Top Stories for Today",
//       body: "Here are the top stories based on your Google Alerts.",
//       date: "Sep 30, 2024",
//       isRead: false,
//     }
//   ];
  
  export const emailData = [
    {
      id: 1,
      sender: "John Doe",
      subject: "Meeting Reminder",
      body: "Just a reminder about tomorrow's meeting at 10 AM.",
      date: "Oct 15, 2024",
      isRead: false,
    },
    {
      id: 2,
      sender: "Jane Smith",
      subject: "Project Update",
      body: "Please review the latest project updates.",
      date: "Oct 14, 2024",
      isRead: true,
    },
    {
      id: 3,
      sender: "Company Newsletter",
      subject: "October Newsletter",
      body: "Check out our latest updates for October.",
      date: "Oct 13, 2024",
      isRead: true,
    },
    {
      id: 4,
      sender: "Support Team",
      subject: "Ticket Resolved",
      body: "Your support ticket has been successfully resolved.",
      date: "Oct 12, 2024",
      isRead: false,
    },
    {
      id: 5,
      sender: "Alice Brown",
      subject: "Lunch Plans",
      body: "Let's have lunch sometime this week.",
      date: "Oct 11, 2024",
      isRead: true,
    },
    {
      id: 6,
      sender: "HR Department",
      subject: "Policy Update",
      body: "We've updated the company policies. Please review the changes.",
      date: "Oct 10, 2024",
      isRead: true,
    },
    {
      id: 7,
      sender: "Bob Anderson",
      subject: "Travel Itinerary",
      body: "Your travel itinerary has been finalized. Please find the details attached.",
      date: "Oct 09, 2024",
      isRead: false,
    },
    {
      id: 8,
      sender: "Marketing Team",
      subject: "Exclusive Offer",
      body: "Get 30% off on your next purchase! Offer valid till end of October.",
      date: "Oct 08, 2024",
      isRead: true,
    },
    {
      id: 9,
      sender: "Sara Lee",
      subject: "Re: Client Feedback",
      body: "Thanks for sending the feedback. I’ll make the necessary updates.",
      date: "Oct 07, 2024",
      isRead: false,
    },
    {
      id: 10,
      sender: "IT Support",
      subject: "Password Reset",
      body: "You requested a password reset. Click here to reset your password.",
      date: "Oct 06, 2024",
      isRead: true,
    },
    {
      id: 11,
      sender: "John Appleseed",
      subject: "Reminder: Annual Performance Review",
      body: "Don't forget about your annual performance review next week.",
      date: "Oct 05, 2024",
      isRead: false,
    },
    {
      id: 12,
      sender: "LinkedIn Updates",
      subject: "You have new connection requests",
      body: "View your new connection requests and messages.",
      date: "Oct 04, 2024",
      isRead: true,
    },
    {
      id: 13,
      sender: "Conference Organizer",
      subject: "Upcoming Conference Details",
      body: "Join us for the upcoming tech conference. Registration is open.",
      date: "Oct 03, 2024",
      isRead: false,
    },
    {
      id: 14,
      sender: "Netflix",
      subject: "New Releases",
      body: "Check out the new movies and shows available this week.",
      date: "Oct 02, 2024",
      isRead: true,
    },
    {
      id: 15,
      sender: "Google Alerts",
      subject: "Top Stories for Today",
      body: "Here are the top stories based on your Google Alerts.",
      date: "Oct 01, 2024",
      isRead: false,
    },
    {
      id: 16,
      sender: "Slack Team",
      subject: "New Slack Message",
      body: "You have a new message in your team channel.",
      date: "Sep 30, 2024",
      isRead: true,
    },
    {
      id: 17,
      sender: "GitHub",
      subject: "Pull Request Merged",
      body: "Your pull request has been successfully merged.",
      date: "Sep 29, 2024",
      isRead: false,
    },
    {
      id: 18,
      sender: "Zoom",
      subject: "Meeting Invitation",
      body: "You've been invited to join a Zoom meeting on Oct 20th.",
      date: "Sep 28, 2024",
      isRead: true,
    },
    {
      id: 19,
      sender: "AWS Notifications",
      subject: "Billing Alert",
      body: "Your AWS usage has exceeded the free tier limits.",
      date: "Sep 27, 2024",
      isRead: false,
    },
    {
      id: 20,
      sender: "Amazon",
      subject: "Your Order Has Shipped",
      body: "Your order #12345 has been shipped and will arrive soon.",
      date: "Sep 26, 2024",
      isRead: true,
    },
    {
      id: 21,
      sender: "Spotify",
      subject: "New Music Released",
      body: "Check out the latest songs from your favorite artists.",
      date: "Sep 25, 2024",
      isRead: false,
    },
    {
      id: 22,
      sender: "Discord",
      subject: "New Message in Your Server",
      body: "You have new messages in your community server.",
      date: "Sep 24, 2024",
      isRead: true,
    },
    {
      id: 23,
      sender: "Udemy",
      subject: "Course Completion Certificate",
      body: "Congrats on completing your course! Here’s your certificate.",
      date: "Sep 23, 2024",
      isRead: false,
    },
    {
      id: 24,
      sender: "PayPal",
      subject: "Payment Received",
      body: "You’ve received a payment of $100.00.",
      date: "Sep 22, 2024",
      isRead: true,
    },
    {
      id: 25,
      sender: "Dribbble",
      subject: "New Job Opportunity",
      body: "A new design job that matches your profile is available.",
      date: "Sep 21, 2024",
      isRead: false,
    },
    {
      id: 26,
      sender: "Reddit",
      subject: "New Comment on Your Post",
      body: "Someone commented on your recent post. Check it out!",
      date: "Sep 20, 2024",
      isRead: true,
    },
    {
      id: 27,
      sender: "Medium",
      subject: "Your Weekly Reading List",
      body: "Here are articles tailored just for you this week.",
      date: "Sep 19, 2024",
      isRead: false,
    },
    {
      id: 28,
      sender: "Dropbox",
      subject: "Shared Folder Notification",
      body: "You have been added to a new shared folder on Dropbox.",
      date: "Sep 18, 2024",
      isRead: true,
    },
    {
      id: 29,
      sender: "YouTube",
      subject: "New Video Alert",
      body: "Your subscribed channel has uploaded a new video.",
      date: "Sep 17, 2024",
      isRead: false,
    },
    {
      id: 30,
      sender: "Stripe",
      subject: "Payment Confirmation",
      body: "Your recent transaction has been processed successfully.",
      date: "Sep 16, 2024",
      isRead: true,
    },
    {
      id: 31,
      sender: "Twitter",
      subject: "New Follower Alert",
      body: "You have a new follower on Twitter!",
      date: "Sep 15, 2024",
      isRead: false,
    },
    {
      id: 32,
      sender: "Trello",
      subject: "New Task Assigned",
      body: "You’ve been assigned a new task in your project board.",
      date: "Sep 14, 2024",
      isRead: true,
    },
    {
      id: 33,
      sender: "Notion",
      subject: "Workspace Update",
      body: "Your Notion workspace has been updated with new templates.",
      date: "Sep 13, 2024",
      isRead: false,
    },
    {
      id: 34,
      sender: "Calendly",
      subject: "Meeting Scheduled",
      body: "Your meeting has been scheduled for next Monday.",
      date: "Sep 12, 2024",
      isRead: true,
    },
    {
      id: 35,
      sender: "Facebook",
      subject: "New Comment on Your Photo",
      body: "Your friend commented on your recent photo. Check it out.",
      date: "Sep 11, 2024",
      isRead: false,
    },
    {
      id: 36,
      sender: "IT Support",
      subject: "Password Reset",
      body: "You requested a password reset. Click here to reset your password.",
      date: "Oct 06, 2024",
      isRead: true,
    },
    {
      id: 37,
      sender: "John Appleseed",
      subject: "Reminder: Annual Performance Review",
      body: "Don't forget about your annual performance review next week.",
      date: "Oct 05, 2024",
      isRead: false,
    },
    {
      id: 38,
      sender: "LinkedIn Updates",
      subject: "You have new connection requests",
      body: "View your new connection requests and messages.",
      date: "Oct 04, 2024",
      isRead: true,
    },
    {
      id: 39,
      sender: "Conference Organizer",
      subject: "Upcoming Conference Details",
      body: "Join us for the upcoming tech conference. Registration is open.",
      date: "Oct 03, 2024",
      isRead: false,
    },
    {
      id: 40,
      sender: "Netflix",
      subject: "New Releases",
      body: "Check out the new movies and shows available this week.",
      date: "Oct 02, 2024",
      isRead: true,
    },
    {
      id: 41,
      sender: "Google Alerts",
      subject: "Top Stories for Today",
      body: "Here are the top stories based on your Google Alerts.",
      date: "Oct 01, 2024",
      isRead: false,
    },
    {
      id: 42,
      sender: "Emma Green",
      subject: "Welcome to the Team!",
      body: "We are excited to have you on board. Let's catch up this week.",
      date: "Sep 30, 2024",
      isRead: true,
    },
    {
      id: 43,
      sender: "Spotify",
      subject: "Weekly Playlist",
      body: "Check out your new curated playlist for this week.",
      date: "Sep 29, 2024",
      isRead: false,
    },
    {
      id: 44,
      sender: "GitHub",
      subject: "Repository Updates",
      body: "Your repository has been updated with the latest changes.",
      date: "Sep 28, 2024",
      isRead: true,
    },
    {
      id: 45,
      sender: "Eventbrite",
      subject: "Upcoming Event: Tech Conference",
      body: "Don't miss the upcoming tech conference. Register today!",
      date: "Sep 27, 2024",
      isRead: false,
    },
    {
      id: 46,
      sender: "Twitter",
      subject: "New Follower",
      body: "You have a new follower. Check out their profile!",
      date: "Sep 26, 2024",
      isRead: true,
    },
    {
      id: 47,
      sender: "Google Photos",
      subject: "Your Memories from 2 Years Ago",
      body: "Check out your photos from this day two years ago.",
      date: "Sep 25, 2024",
      isRead: false,
    },
    {
      id: 48,
      sender: "Amazon",
      subject: "Your Order Has Shipped",
      body: "Your order has been shipped and will arrive soon.",
      date: "Sep 24, 2024",
      isRead: true,
    },
    {
      id: 49,
      sender: "Slack",
      subject: "New Direct Message",
      body: "You have a new direct message from your colleague.",
      date: "Sep 23, 2024",
      isRead: false,
    },
    {
      id: 50,
      sender: "Facebook",
      subject: "New Friend Request",
      body: "You have a new friend request. Accept it now!",
      date: "Sep 22, 2024",
      isRead: true,
    },
    {
      id: 51,
      sender: "Dropbox",
      subject: "Your File is Ready",
      body: "The file you uploaded is ready for download.",
      date: "Sep 21, 2024",
      isRead: false,
    },
    {
      id: 52,
      sender: "Airbnb",
      subject: "Upcoming Trip",
      body: "Your upcoming trip is approaching. Get ready for your stay!",
      date: "Sep 20, 2024",
      isRead: true,
    },
    {
      id: 53,
      sender: "Uber",
      subject: "Your Ride Receipt",
      body: "Thank you for riding with us. Here is your ride receipt.",
      date: "Sep 19, 2024",
      isRead: false,
    },
    {
      id: 54,
      sender: "Coursera",
      subject: "New Course Recommendations",
      body: "Check out these new courses tailored just for you.",
      date: "Sep 18, 2024",
      isRead: true,
    },
    {
      id: 55,
      sender: "Pinterest",
      subject: "New Pins Based on Your Interest",
      body: "Explore new pins related to your interests.",
      date: "Sep 17, 2024",
      isRead: false,
    },
    {
      id: 56,
      sender: "Google Play",
      subject: "New Apps and Games",
      body: "Check out the latest apps and games available on Google Play.",
      date: "Sep 16, 2024",
      isRead: true,
    },
    {
      id: 57,
      sender: "Disney+",
      subject: "New Episodes Available",
      body: "Catch up on the latest episodes of your favorite shows.",
      date: "Sep 15, 2024",
      isRead: false,
    },
    {
      id: 58,
      sender: "Quora",
      subject: "New Answers to Your Questions",
      body: "Here are new answers to the questions you posted.",
      date: "Sep 14, 2024",
      isRead: true,
    },
    {
      id: 59,
      sender: "Stack Overflow",
      subject: "New Comment on Your Post",
      body: "Someone commented on your post. Check it out!",
      date: "Sep 13, 2024",
      isRead: false,
    },
    {
      id: 60,
      sender: "Kickstarter",
      subject: "Project Update",
      body: "A project you backed has posted a new update.",
      date: "Sep 12, 2024",
      isRead: true,
    },
    {
      id: 61,
      sender: "Trello",
      subject: "Task Assignment",
      body: "You have been assigned a new task on your Trello board.",
      date: "Sep 11, 2024",
      isRead: true,
    }
  ]


  