export const emailData = [
    {
      id: 1,
      sender: "John Doe",
      subject: "Meeting Reminder",
      body: "Just a reminder about tomorrow's meeting at 10 AM.",
      date: "Oct 15, 2024",
      isRead: false,
    },
    {
      id: 2,
      sender: "Jane Smith",
      subject: "Project Update",
      body: "Please review the latest project updates.",
      date: "Oct 14, 2024",
      isRead: true,
    },
    {
      id: 3,
      sender: "Company Newsletter",
      subject: "October Newsletter",
      body: "Check out our latest updates for October.",
      date: "Oct 12, 2024",
      isRead: true,
    },
    {
      id: 4,
      sender: "Support Team",
      subject: "Ticket Resolved",
      body: "Your support ticket has been successfully resolved.",
      date: "Oct 11, 2024",
      isRead: false,
    },
    {
      id: 5,
      sender: "Alice Brown",
      subject: "Lunch Plans",
      body: "Let's have lunch sometime this week.",
      date: "Oct 10, 2024",
      isRead: true,
    },
    {
      id: 6,
      sender: "HR Department",
      subject: "Policy Update",
      body: "We've updated the company policies. Please review the changes.",
      date: "Oct 09, 2024",
      isRead: true,
    },
    {
      id: 7,
      sender: "Bob Anderson",
      subject: "Travel Itinerary",
      body: "Your travel itinerary has been finalized. Please find the details attached.",
      date: "Oct 08, 2024",
      isRead: false,
    },
    {
      id: 8,
      sender: "Marketing Team",
      subject: "Exclusive Offer",
      body: "Get 30% off on your next purchase! Offer valid till end of October.",
      date: "Oct 07, 2024",
      isRead: true,
    },
    {
      id: 9,
      sender: "Sara Lee",
      subject: "Re: Client Feedback",
      body: "Thanks for sending the feedback. I’ll make the necessary updates.",
      date: "Oct 06, 2024",
      isRead: false,
    },
    {
      id: 10,
      sender: "IT Support",
      subject: "Password Reset",
      body: "You requested a password reset. Click here to reset your password.",
      date: "Oct 05, 2024",
      isRead: true,
    },
    {
      id: 11,
      sender: "John Appleseed",
      subject: "Reminder: Annual Performance Review",
      body: "Don't forget about your annual performance review next week.",
      date: "Oct 04, 2024",
      isRead: false,
    },
    {
      id: 12,
      sender: "LinkedIn Updates",
      subject: "You have new connection requests",
      body: "View your new connection requests and messages.",
      date: "Oct 03, 2024",
      isRead: true,
    },
    {
      id: 13,
      sender: "Conference Organizer",
      subject: "Upcoming Conference Details",
      body: "Join us for the upcoming tech conference. Registration is open.",
      date: "Oct 02, 2024",
      isRead: false,
    },
    {
      id: 14,
      sender: "Netflix",
      subject: "New Releases",
      body: "Check out the new movies and shows available this week.",
      date: "Oct 01, 2024",
      isRead: true,
    },
    {
      id: 15,
      sender: "Google Alerts",
      subject: "Top Stories for Today",
      body: "Here are the top stories based on your Google Alerts.",
      date: "Sep 30, 2024",
      isRead: false,
    }
  ];
  